"use client";

import { useState } from "react";
import { useSubmitTurnMutation } from "@/services/api/diagnosticApi";
import { getApiErrorMessage } from "@/lib/errors";
import type { DiagnosticAttempt } from "@/types/api";

export function AdaptiveQuestionForm({
  attempt,
  onUpdated,
}: {
  attempt: DiagnosticAttempt;
  onUpdated: (next: DiagnosticAttempt) => void;
}) {
  const turn = attempt.active_turn;
  const [answer, setAnswer] = useState(turn?.answer_text || "");
  const [submitTurn, { isLoading, error }] = useSubmitTurnMutation();

  if (!turn || attempt.status === "COMPLETED") {
    return (
      <p className="p-6 text-sm text-on-surface-variant">
        {attempt.status === "COMPLETED"
          ? "Assessment complete."
          : "Generating the next question…"}
      </p>
    );
  }

  async function onSubmit(e: React.FormEvent) {
    e.preventDefault();
    if (!turn) return;
    const next = await submitTurn({
      attemptId: attempt.id,
      body: { turn_id: turn.id, answer_text: answer },
    }).unwrap();
    setAnswer("");
    onUpdated(next);
  }

  return (
    <div className="mx-auto flex w-full max-w-3xl flex-col gap-6 px-6 py-10">
      <div className="flex items-center justify-between gap-3">
        <div>
          <p className="font-[family-name:var(--font-jetbrains-mono)] text-[12px] uppercase tracking-[0.08em] text-on-surface-variant">
            {attempt.diagnostic_title}
          </p>
          <h1 className="mt-1 headline-md text-on-surface">
            {turn.stage.replaceAll("_", " ")}
            {turn.skill?.name ? ` · ${turn.skill.name}` : ""}
          </h1>
          {turn.question_payload?.generation_source === "bank_fallback" ? (
            <p className="mt-1 body-sm text-error">
              AI generation failed — showing a fallback bank question.
            </p>
          ) : (
            <p className="mt-1 font-[family-name:var(--font-jetbrains-mono)] text-[12px] text-tertiary">
              Generated by Gemini
            </p>
          )}
        </div>
        <span className="rounded bg-surface-container-high px-2 py-1 font-[family-name:var(--font-jetbrains-mono)] text-[12px] text-on-surface-variant">
          Turn {turn.ordering}
        </span>
      </div>

      <div className="rounded-xl border border-outline-variant/40 bg-surface-container p-6">
        <p className="body-lg whitespace-pre-wrap text-on-surface">
          {turn.prompt_text}
        </p>
        {Array.isArray(turn.question_payload?.requirements) &&
        (turn.question_payload.requirements as string[]).length ? (
          <ul className="mt-4 list-disc space-y-1 pl-5 body-sm text-on-surface-variant">
            {(turn.question_payload.requirements as string[]).map((r) => (
              <li key={r}>{r}</li>
            ))}
          </ul>
        ) : null}
      </div>

      <form className="flex flex-col gap-4" onSubmit={onSubmit}>
        <label
          htmlFor="adaptive-answer"
          className="font-[family-name:var(--font-jetbrains-mono)] text-[12px] uppercase tracking-[0.06em] text-on-surface-variant"
        >
          Your answer
        </label>
        <textarea
          id="adaptive-answer"
          value={answer}
          onChange={(e) => setAnswer(e.target.value)}
          rows={turn.question_type === "CODE" ? 14 : 8}
          className="w-full rounded-xl border border-outline-variant/50 bg-surface-dim p-4 font-[family-name:var(--font-jetbrains-mono)] text-[13px] text-on-surface outline-none focus:border-primary"
          placeholder={
            turn.question_type === "CODE"
              ? "Paste code or write your solution…"
              : "Write your reasoning…"
          }
        />
        {error ? (
          <p className="body-sm text-error">{getApiErrorMessage(error)}</p>
        ) : null}
        <button
          type="submit"
          disabled={isLoading || !answer.trim()}
          className="self-end rounded-xl bg-primary px-8 py-3 headline-sm text-on-primary disabled:opacity-60"
        >
          {isLoading ? "Evaluating…" : "Submit answer"}
        </button>
      </form>
    </div>
  );
}
